### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by sel471ofc** [ibrahim-bedir/filament-dynamic-settings-page#10]
<img width="1051" alt="Screenshot 2023-03-30 at 15 02 58" src="https://user-images.githubusercontent.com/127332499/228770560-8268b354-26fd-4aad-8026-c34ff3f1346c.png">

**Comment by petrisorcraciun** [comment]
Check 'minimum-stability' in composer.json. The library isn't versioned. It does not have a stable version.

**Comment by magarrent** [comment]
@ibrahim-bedir could you make a release please?

**Comment by rahmatsubandi** [comment]
I have the same problem. Can the author update it?
<img width="1203" alt="Screenshot 2023-06-27 at 01 31 34" src="https://github.com/ibrahim-bedir/filament-dynamic-settings-page/assets/61180713/b57c4cce-4daf-4605-86ee-b0380ed39ee3">

**Comment by ibrahim-bedir** [comment]
please try again.

**Comment by ibrahim-bedir** [comment]
> Check 'minimum-stability' in composer.json. The library isn't versioned. It does not have a stable version.

stable version added.

please try again and reply.

**Comment by rahmatsubandi** [comment]
great, it works.
Yeah it's version related, I didn't pay attention to it haha 😆 . Thank You!

**Comment by ibrahim-bedir** [comment]
that's my fault, You're welcome.
